FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
ARG PUBLIC_SITE_TITLE
ARG PUBLIC_SITE_URL
ARG PUBLIC_SITE_DESCRIPTION
ARG PUBLIC_PATREON_URL
ARG PUBLIC_FACEBOOK_URL
ARG PUBLIC_GOOGLE_PLAY_URL
ARG PUBLIC_APP_STORE_URL
ARG PUBLIC_CHROME_EXTENSION_URL
ARG API_URL
ENV \
    PUBLIC_SITE_TITLE=$PUBLIC_SITE_TITLE \
    PUBLIC_SITE_URL=$PUBLIC_SITE_URL \
    PUBLIC_SITE_DESCRIPTION=$PUBLIC_SITE_DESCRIPTION \
    PUBLIC_PATREON_URL=$PUBLIC_PATREON_URL \
    PUBLIC_FACEBOOK_URL=$PUBLIC_FACEBOOK_URL \
    PUBLIC_GOOGLE_PLAY_URL=$PUBLIC_GOOGLE_PLAY_URL \
    PUBLIC_APP_STORE_URL=$PUBLIC_APP_STORE_URL \
    PUBLIC_CHROME_EXTENSION_URL=$PUBLIC_CHROME_EXTENSION_URL \
    API_URL=$API_URL
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]