FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
ARG PUBLIC_SITE_TITLE
ARG PUBLIC_SITE_URL
ARG PUBLIC_SITE_DESCRIPTION
ARG PUBLIC_PATREON_URL
ARG PUBLIC_FACEBOOK_URL
ARG PUBLIC_GITHUB_LINK
ARG PUBLIC_GOOGLE_PLAY_URL
ARG PUBLIC_APP_STORE_URL
ARG PUBLIC_CHROME_EXTENSION_URL
ARG PUBLIC_INFORMATION_REMOVAL_FORMSPREE_URL
ARG API_URL
ARG PUBLIC_FIREBASE_API_KEY
ARG PUBLIC_FIREBASE_AUTH_DOMAIN
ARG PUBLIC_FIREBASE_PROJECT_ID
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_CLIENT_EMAIL
ARG FIREBASE_PRIVATE_KEY
ENV \
    PUBLIC_SITE_TITLE=$PUBLIC_SITE_TITLE \
    PUBLIC_SITE_URL=$PUBLIC_SITE_URL \
    PUBLIC_SITE_DESCRIPTION=$PUBLIC_SITE_DESCRIPTION \
    PUBLIC_PATREON_URL=$PUBLIC_PATREON_URL \
    PUBLIC_FACEBOOK_URL=$PUBLIC_FACEBOOK_URL \
    PUBLIC_GITHUB_LINK=$PUBLIC_GITHUB_LINK \
    PUBLIC_GOOGLE_PLAY_URL=$PUBLIC_GOOGLE_PLAY_URL \
    PUBLIC_APP_STORE_URL=$PUBLIC_APP_STORE_URL \
    PUBLIC_CHROME_EXTENSION_URL=$PUBLIC_CHROME_EXTENSION_URL \
    PUBLIC_INFORMATION_REMOVAL_FORMSPREE_URL=$PUBLIC_INFORMATION_REMOVAL_FORMSPREE_URL \
    API_URL=$API_URL \
    PUBLIC_FIREBASE_API_KEY=$PUBLIC_FIREBASE_API_KEY \
    PUBLIC_FIREBASE_AUTH_DOMAIN=$PUBLIC_FIREBASE_AUTH_DOMAIN \
    PUBLIC_FIREBASE_PROJECT_ID=$PUBLIC_FIREBASE_PROJECT_ID \
    FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID \
    FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL \
    FIREBASE_PRIVATE_KEY=$FIREBASE_PRIVATE_KEY
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "build" ]